DASHBOARD_HTML = r'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PuroCuento · Centro de atención</title>
<style>
:root{--nav:#111827;--nav2:#1f2937;--ink:#172033;--muted:#697386;--line:#e5e9f0;--bg:#f4f6f9;--card:#fff;--brand:#e43e55;--brand2:#b61f38;--green:#087a5b;--amber:#9a6700;--blue:#315ea8;--danger:#b42318}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--ink)}button,input,textarea,select{font:inherit}button{cursor:pointer}
.shell{min-height:100vh;display:grid;grid-template-columns:230px 1fr}.sidebar{background:var(--nav);color:#fff;padding:22px 14px;display:flex;flex-direction:column;gap:22px}.brand{display:flex;align-items:center;gap:11px;padding:0 8px}.logo{width:34px;height:34px;border-radius:10px;background:var(--brand);display:grid;place-items:center;font-weight:900}.brand small{display:block;color:#9ca3af;margin-top:2px}.nav{display:grid;gap:5px}.nav button{background:transparent;border:0;color:#cbd5e1;text-align:left;padding:11px 12px;border-radius:9px}.nav button:hover,.nav button.active{background:var(--nav2);color:#fff}.online{margin-top:auto;color:#a7f3d0;font-size:12px;padding:10px}.online i{display:inline-block;width:8px;height:8px;background:#34d399;border-radius:50%;margin-right:7px}
.content{min-width:0}.topbar{height:68px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 24px;gap:14px}.topbar h1{font-size:18px;margin:0}.topbar .sub{color:var(--muted);font-size:13px;margin-left:auto}.page{padding:20px}.hidden{display:none!important}
.stats{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:12px;margin-bottom:16px}.stat{background:#fff;border:1px solid var(--line);border-radius:12px;padding:15px}.stat span{display:block;color:var(--muted);font-size:12px}.stat b{display:block;font-size:24px;margin-top:6px}.stat.alert b{color:var(--danger)}
.inbox{height:calc(100vh - 142px);display:grid;grid-template-columns:310px minmax(420px,1fr) 330px;background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden;box-shadow:0 8px 28px #1720330b}.panel{min-width:0;border-right:1px solid var(--line);display:flex;flex-direction:column}.panel:last-child{border:0}.panel-head{min-height:58px;border-bottom:1px solid var(--line);padding:12px 15px;display:flex;align-items:center;gap:8px}.panel-head strong{margin-right:auto}.search{width:100%;border:1px solid var(--line);border-radius:9px;padding:9px 10px;background:#f8fafc}.list{overflow:auto;flex:1}.conversation{padding:13px 14px;border-bottom:1px solid var(--line);cursor:pointer;position:relative}.conversation:hover,.conversation.active{background:#fff4f6}.conversation .row{display:flex;gap:8px;align-items:center}.conversation .name{font-weight:750;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.conversation .time{margin-left:auto;color:var(--muted);font-size:11px}.conversation .preview{font-size:13px;color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin:6px 0}.dot-unread{width:8px;height:8px;border-radius:50%;background:var(--brand)}
.badge{display:inline-flex;align-items:center;padding:4px 7px;border-radius:999px;font-weight:750;font-size:10px;background:#edf1f6;color:#4b5563;margin-right:4px}.badge.wait{background:#fff1c7;color:#7c5700}.badge.human{background:#dff7ed;color:#075c45}.badge.ai{background:#e7efff;color:#264e9b}.badge.high{background:#ffe4e8;color:#a5142b}
.thread-head{display:flex;align-items:center;gap:9px}.thread-head .identity{margin-right:auto}.thread-head small{display:block;color:var(--muted)}.btn{border:0;border-radius:8px;padding:8px 10px;font-weight:700;background:#edf1f6;color:var(--ink)}.btn.primary{background:var(--brand);color:white}.btn.primary:hover{background:var(--brand2)}.btn.blue{background:#e7efff;color:#244d92}.btn.danger{background:#fff0f0;color:var(--danger)}.btn:disabled{opacity:.45;cursor:not-allowed}
#thread{flex:1;overflow:auto;padding:20px;background:#f2eee8}.bubble{max-width:78%;border-radius:13px;padding:10px 12px;margin:8px 0;background:#fff;box-shadow:0 1px 2px #17203318;white-space:pre-wrap}.bubble.outbound{margin-left:auto;background:#d9fdd3}.bubble .sender{font-size:10px;color:var(--muted);font-weight:800;margin-bottom:4px}.bubble .meta{text-align:right;color:#758092;font-size:9px;margin-top:5px}.empty{margin:auto;color:var(--muted);padding:30px;text-align:center}.composer{border-top:1px solid var(--line);padding:12px;display:flex;gap:8px}.composer textarea{flex:1;resize:none;border:1px solid #cfd5df;border-radius:9px;padding:10px}.composer-note{font-size:10px;color:var(--muted);padding:0 12px 9px}
.brief{overflow:auto;flex:1;padding:15px}.brief h3{margin:3px 0 12px}.field{margin-bottom:12px}.field label{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.06em;font-weight:800;margin-bottom:4px}.field div,.field input,.field textarea,.field select{width:100%;font-size:13px}.field input,.field textarea,.field select{border:1px solid var(--line);border-radius:8px;padding:8px}.missing{padding:10px;border-radius:9px;background:#fff7e0;color:#785600;font-size:12px}.risk{padding:10px;border-radius:9px;background:#fff0f2;color:#97152a;font-size:12px}.source{font-size:11px;color:var(--blue)}
.card{background:#fff;border:1px solid var(--line);border-radius:13px;overflow:hidden}.card-head{padding:15px 17px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:10px}.card-head strong{margin-right:auto}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:11px 13px;border-bottom:1px solid var(--line);vertical-align:top}th{background:#f8fafc;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em}td.actions{white-space:nowrap}.knowledge-grid{display:grid;grid-template-columns:360px 1fr;gap:15px}.editor{padding:16px;display:grid;gap:11px}.editor label{color:var(--muted);font-size:11px;font-weight:700}.editor input,.editor textarea,.editor select{width:100%;border:1px solid var(--line);border-radius:8px;padding:9px;margin-top:4px}.editor textarea{min-height:180px;resize:vertical}.notice{background:#eef5ff;border:1px solid #d6e6ff;color:#244d92;padding:11px 13px;border-radius:10px;font-size:12px;margin-bottom:14px}
.toast{position:fixed;right:20px;bottom:20px;background:#111827;color:#fff;padding:11px 14px;border-radius:9px;box-shadow:0 8px 25px #0003;z-index:10}.toast.error{background:#8f1526}
@media(max-width:1100px){.stats{grid-template-columns:repeat(3,1fr)}.inbox{grid-template-columns:270px 1fr}.detail-panel{display:none}.knowledge-grid{grid-template-columns:1fr}}
@media(max-width:760px){.shell{display:block}.sidebar{padding:10px;display:block}.brand{margin-bottom:9px}.nav{display:flex;overflow:auto}.nav button{white-space:nowrap}.online{display:none}.topbar{height:56px;padding:0 14px}.topbar .sub{display:none}.page{padding:8px}.stats{grid-template-columns:repeat(2,1fr)}.stat{padding:10px}.inbox{height:auto;display:block}.list-panel{height:260px}.chat-panel{height:650px;border-top:1px solid var(--line)}.thread-head{flex-wrap:wrap}.bubble{max-width:90%}}
</style></head>
<body><div class="shell"><aside class="sidebar"><div class="brand"><div class="logo">PC</div><div><b>PuroCuento</b><small>Centro de atención</small></div></div><nav class="nav">
<button class="active" data-page="inbox">Bandeja de entrada</button><button data-page="projects">Proyectos</button><button data-page="knowledge">Conocimiento</button><button data-page="audit">Actividad</button></nav><div class="online"><i></i>Sistema operativo</div></aside>
<main class="content"><header class="topbar"><h1 id="pageTitle">Bandeja de entrada</h1><span class="sub">WhatsApp · IA supervisada · equipo humano</span></header>
<div class="page"><div id="stats" class="stats"></div>
<section id="page-inbox" class="page-section"><div class="inbox">
  <div class="panel list-panel"><div class="panel-head"><input id="convSearch" class="search" placeholder="Buscar conversación"></div><div id="conversations" class="list"></div></div>
  <div class="panel chat-panel"><div class="panel-head thread-head"><div class="identity"><strong id="threadName">Selecciona una conversación</strong><small id="threadState">Sin conversación activa</small></div><button id="takeBtn" class="btn primary" onclick="changeState('HUMAN_ACTIVE')">Tomar control</button><button id="aiBtn" class="btn blue" onclick="changeState('AI_ACTIVE')">Devolver a IA</button><button id="newBtn" class="btn" onclick="newProject()">Nuevo proyecto</button><button id="closeBtn" class="btn" onclick="changeState('CLOSED')">Cerrar</button></div><div id="thread"><div class="empty">Los mensajes del cliente aparecerán aquí.</div></div><div class="composer"><textarea id="reply" rows="2" placeholder="Respuesta del equipo PuroCuento…"></textarea><button class="btn primary" onclick="sendReply()">Enviar</button></div><div class="composer-note">El envío humano activa el modo humano. La IA permanece en silencio hasta que el equipo la reactive.</div></div>
  <div class="panel detail-panel"><div class="panel-head"><strong>Briefing del proyecto</strong></div><div id="brief" class="brief"><div class="empty">Selecciona una conversación.</div></div></div>
</div></section>
<section id="page-projects" class="page-section hidden"><div class="card"><div class="card-head"><strong>Proyectos cualificados</strong><span class="badge high">Revisión humana obligatoria para alto valor</span></div><div class="table-wrap"><table><thead><tr><th>Contacto</th><th>Proyecto</th><th>Servicios</th><th>Datos</th><th>Riesgo</th><th>Estado</th></tr></thead><tbody id="projectsBody"></tbody></table></div></div></section>
<section id="page-knowledge" class="page-section hidden"><div class="notice">Solo el contenido marcado como <b>Aprobado para IA</b> puede usarse en respuestas. Los cambios quedan versionados y registrados.</div><div class="knowledge-grid"><div class="card"><div class="card-head"><strong>Base de conocimiento</strong><button class="btn primary" onclick="newKnowledge()">Nuevo</button></div><div id="knowledgeList" class="list"></div></div><div class="card"><div class="card-head"><strong>Editor y aprobación</strong></div><form class="editor" onsubmit="saveKnowledge(event)"><input type="hidden" id="kId"><label>Título<input id="kTitle" required></label><label>Categoría<input id="kCategory" required></label><label>Fuente oficial<input id="kSource" type="url" placeholder="https://purocuento.es/..."></label><label>Contenido<textarea id="kContent" required></textarea></label><label>Visibilidad<select id="kStatus"><option value="draft">Borrador — no visible para IA</option><option value="approved">Aprobado para IA</option><option value="archived">Archivado</option></select></label><button class="btn primary" type="submit">Guardar cambio</button></form></div></div></section>
<section id="page-audit" class="page-section hidden"><div class="card"><div class="card-head"><strong>Registro de actividad</strong><span class="source">Estados, envíos, aprobaciones y handoffs</span></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Actor</th><th>Acción</th><th>Contacto</th><th>Detalle</th></tr></thead><tbody id="auditBody"></tbody></table></div></div></section>
</div></main></div><div id="toast" class="toast hidden"></div>
<script>
let selected='',conversations=[],knowledge=[];const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stateLabel={AI_ACTIVE:'IA activa',WAITING_FOR_HUMAN:'Esperando al equipo',HUMAN_ACTIVE:'Equipo atendiendo',CLOSED:'Cerrada'};
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className='toast'+(error?' error':'');setTimeout(()=>el.className='toast hidden',2600)}
async function api(url,options){const r=await fetch(url,options);let body={};try{body=await r.json()}catch(e){}if(!r.ok)throw new Error(body.error||'No se pudo completar la acción');return body}
function showPage(page){document.querySelectorAll('.page-section').forEach(x=>x.classList.add('hidden'));$('page-'+page).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('pageTitle').textContent={inbox:'Bandeja de entrada',projects:'Proyectos',knowledge:'Base de conocimiento',audit:'Actividad y auditoría'}[page];if(page==='projects')loadProjects();if(page==='knowledge')loadKnowledge();if(page==='audit')loadAudit()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
async function loadSummary(){const s=await api('/dashboard/api/summary');const cells=[['Conversaciones',s.conversations],['Esperando equipo',s.waiting],['Equipo activo',s.human_active],['Alto valor',s.high_value],['Alertas de entrega',s.notification_failures],['Almacenamiento',s.storage==='persistent-volume'?'Persistente':'Temporal']];$('stats').innerHTML=cells.map((x,i)=>`<div class="stat ${(i===4&&x[1])||(i===5&&s.storage!=='persistent-volume')?'alert':''}"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('')}
async function loadConversations(){conversations=await api('/dashboard/api/conversations');renderConversations();if(selected)await loadThread()}
function renderConversations(){const q=$('convSearch').value.toLowerCase();const list=conversations.filter(c=>(c.phone+' '+(c.name||'')+' '+(c.company||'')+' '+(c.last_message||'')).toLowerCase().includes(q));$('conversations').innerHTML=list.map(c=>{const label=c.name||c.company||c.phone.replace('whatsapp:','');const cls=c.state==='WAITING_FOR_HUMAN'?'wait':c.state==='HUMAN_ACTIVE'?'human':'ai';return `<div class="conversation ${c.phone===selected?'active':''}" data-phone="${esc(c.phone)}"><div class="row">${c.unread?'<i class="dot-unread"></i>':''}<span class="name">${esc(label)}</span><span class="time">${esc((c.updated_at||'').slice(11,16))}</span></div><div class="preview">${esc(c.last_message||'Sin mensajes')}</div><span class="badge ${cls}">${esc(stateLabel[c.state]||c.state)}</span>${c.high_value?'<span class="badge high">Alto valor</span>':''}</div>`}).join('')||'<div class="empty">No hay conversaciones</div>';document.querySelectorAll('.conversation').forEach(el=>el.onclick=()=>selectConversation(el.dataset.phone))}
$('convSearch').oninput=renderConversations;
async function selectConversation(phone){selected=phone;renderConversations();await loadThread()}
async function loadThread(){const x=await api('/dashboard/api/thread?phone='+encodeURIComponent(selected));const c=x.conversation||{};$('threadName').textContent=(x.project&&x.project.name)||selected.replace('whatsapp:','');$('threadState').textContent=(stateLabel[c.state]||c.state)+' · '+(c.priority==='HIGH'?'prioridad alta':'prioridad normal');$('thread').innerHTML=x.messages.map(m=>`<div class="bubble ${m.direction}"><div class="sender">${m.sender==='ai'?'Asistente supervisado':m.sender==='human'?'Equipo PuroCuento':m.sender==='system'?'Sistema':'Cliente'}</div>${esc(m.body)}<div class="meta">${esc((m.created_at||'').replace('T',' ').slice(0,16))}${m.delivery_status?' · '+esc(m.delivery_status):''}</div></div>`).join('')||'<div class="empty">Sin mensajes.</div>';$('thread').scrollTop=$('thread').scrollHeight;renderBrief(x.project,c);const locked=c.state!=='HUMAN_ACTIVE';$('reply').disabled=locked;$('reply').placeholder=locked?'Toma el control para responder…':'Respuesta del equipo PuroCuento…'}
function renderBrief(p,c){if(!p){$('brief').innerHTML='<div class="empty">El briefing estructurado aparecerá cuando el cliente describa su proyecto.</div>';return}const f=(label,value)=>`<div class="field"><label>${label}</label><div>${esc(value||'—')}</div></div>`;$('brief').innerHTML=`<h3>${p.high_value?'Proyecto de alto valor':'Proyecto en cualificación'}</h3>${p.high_value?`<div class="risk"><b>Revisión humana obligatoria</b><br>${esc((p.risk_reasons||[]).join(' · '))}</div><br>`:''}${f('Nombre',p.name)}${f('Empresa / productora',p.company)}${f('Tipo',p.project_type)}${f('Servicios',(p.services||[]).join(', '))}${f('Fecha',p.dates)}${f('Localización',p.location)}${f('Personas',p.people)}${f('Logística',p.logistics)}${p.missing&&p.missing.length?`<div class="missing"><b>Datos pendientes</b><br>${esc(p.missing.join(' · '))}</div>`:''}`}
async function changeState(state){if(!selected)return toast('Selecciona una conversación',true);try{await api('/dashboard/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:selected,state})});toast(state==='HUMAN_ACTIVE'?'Control transferido al equipo':state==='AI_ACTIVE'?'IA reactivada':'Conversación cerrada');await loadConversations();await loadSummary()}catch(e){toast(e.message,true)}}
async function newProject(){if(!selected)return toast('Selecciona una conversación',true);if(!confirm('¿Archivar el proyecto actual y empezar uno nuevo para este contacto?'))return;try{await api('/dashboard/api/new-project',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:selected})});toast('Nuevo proyecto creado; el historial anterior no se usará por la IA');await loadConversations();await loadSummary()}catch(e){toast(e.message,true)}}
async function sendReply(){const body=$('reply').value.trim();if(!selected||!body)return;try{await api('/dashboard/api/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:selected,body})});$('reply').value='';toast('Mensaje enviado por el equipo');await loadConversations()}catch(e){toast(e.message,true)}}
async function loadProjects(){const rows=await api('/dashboard/api/projects');$('projectsBody').innerHTML=rows.map(p=>`<tr><td><b>${esc(p.name||p.phone.replace('whatsapp:',''))}</b><br><small>${esc(p.company||p.contact||'')}</small></td><td>${esc(p.project_type||'Por definir')}<br><small>${esc(p.location||'')} ${esc(p.dates||'')}</small></td><td>${esc((p.services||[]).join(', ')||'Por definir')}</td><td>${p.people?esc(p.people)+' personas':''}<br><small>${esc(p.logistics||'')}</small></td><td>${p.high_value?'<span class="badge high">Alto valor</span><br>'+esc((p.risk_reasons||[]).join(' · ')):'Normal'}</td><td>${esc(p.status)}</td></tr>`).join('')||'<tr><td colspan="6">Aún no hay proyectos cualificados.</td></tr>'}
async function loadKnowledge(){knowledge=await api('/dashboard/api/knowledge');$('knowledgeList').innerHTML=knowledge.map(k=>`<div class="conversation" data-kid="${esc(k.id)}"><div class="row"><span class="name">${esc(k.title)}</span></div><div class="preview">${esc(k.category)} · v${esc(k.version)}</div><span class="badge ${k.status==='approved'?'human':k.status==='draft'?'wait':''}">${k.status==='approved'?'Aprobado':k.status==='draft'?'Borrador':'Archivado'}</span></div>`).join('');document.querySelectorAll('[data-kid]').forEach(el=>el.onclick=()=>editKnowledge(el.dataset.kid))}
function newKnowledge(){$('kId').value='';$('kTitle').value='';$('kCategory').value='General';$('kSource').value='https://purocuento.es/';$('kContent').value='';$('kStatus').value='draft'}
function editKnowledge(id){const k=knowledge.find(x=>x.id===id);if(!k)return;$('kId').value=k.id;$('kTitle').value=k.title;$('kCategory').value=k.category;$('kSource').value=k.source_url||'';$('kContent').value=k.content;$('kStatus').value=k.status}
async function saveKnowledge(e){e.preventDefault();const body={id:$('kId').value||undefined,title:$('kTitle').value,category:$('kCategory').value,source_url:$('kSource').value,content:$('kContent').value,status:$('kStatus').value};try{await api('/dashboard/api/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Conocimiento guardado y registrado');await loadKnowledge();await loadSummary()}catch(err){toast(err.message,true)}}
async function loadAudit(){const rows=await api('/dashboard/api/audit');$('auditBody').innerHTML=rows.map(a=>`<tr><td>${esc((a.created_at||'').replace('T',' ').slice(0,19))}</td><td>${esc(a.actor)}</td><td><b>${esc(a.action)}</b></td><td>${esc((a.phone||'').replace('whatsapp:',''))}</td><td>${esc(a.details)}</td></tr>`).join('')}
async function boot(){try{await Promise.all([loadSummary(),loadConversations()])}catch(e){toast(e.message,true)}}boot();setInterval(()=>{loadSummary().catch(()=>{});loadConversations().catch(()=>{})},5000);
</script></body></html>'''
